### PR TITLE
New features and bug fixes

### PR DESCRIPTION
**Pull request by eemmiirr**
Fixed couple of issues. 
Please merge after https://github.com/docker-java/docker-java/pull/194 is merged.
The same bug exists in the docker-java library

### CODE REVIEW

**Comment by alexec** [comment]
OK. I've cherry picked your changes as they could not be merged normally. Can you check that the master version works for you?

**Comment by eemmiirr** [comment]
Actually it won't work since the PR above was merged into 1.1.1-SNAPSHOT of docker-java library. The bug was also there present which enforces the deletion of images regardless of what is supplied. So we have to wait until it's released

**Comment by eemmiirr** [comment]
Btw this has to be merged too https://github.com/eemmiirr/docker-java-orchestration/commit/e2a8703a668692f4267ef21b9d228f33c9a2a8a5 to fix the bug when naming images. 

When the image is built it's tagged with one name. During the start phase the plugin tries to find the image by some other name which results that is never found and rebuild over again

**Comment by alexec** [comment]
HI,

I think I have fixed that by modifying the `imageExists` method. I'm running a bunch of tests before releasing now.

Alex

**Comment by eemmiirr** [comment]
Hi,

it works perfectly except that it removes always the intermediate images. You have to wait until the docker-java library with the patch is released

**Pull request closed without merging**
