### PR TITLE
Add sslVerify=true/false for self-signed HTTPS healthchecks

### PR DESCRIPTION
**Pull request by scooterGrun**
Add a feature toggle (sslVerify) in Ping to allow self-signed certificate HTTPS connections when running health check.  

```
healthChecks:
  pings:
    - url: https://${maven.docker.container.ip}:8446/info
      timeout: 60000
      pattern: \"version\":\"${project.version}\"
      sslVerify: false
```

### CODE REVIEW

**Comment by alexec** [comment]
Looks pretty good. I'm wondering how it can be tested. Do you have any thoughts?

**Comment by alexec** [comment]
@scooterGrun I've merged this (sorry, I've been bit busy) I was wondering if SSL verification should be false by default?

**Comment by scooterGrun** [comment]
Hi @alexec, 
I set sslVerify=false by default so that existing behavior wasn't affected, in case others were relying on certificate verification.
I am still endeavoring to write an IT test for it, although on my first attempt I found I needed JCE installed to serve. Will keep you posted on that.

**Comment by alexec** [comment]
Ok. I'll leave it disabled for version 2.10.1. 

I've a jetty web app that creates a self signed certificate if you want an example:

https://github.com/selenium-webdriver-in-practice/source/blob/master/pom.xml

**Pull request merged**
